### ISSUE TITLE
Add support for finding if a HasOne and HasMany contains data

### ISSUE THREAD

**Issue by lukesleeman** [kamikat/moshi-jsonapi#12] opened 2016-09-07 00:26 UTC
The HasOne.get() method throws a ResourceNotFoundException if there is no resource.  This leads to clunky code if you want to return null or some default value:

```
            try{
                return jobTitle.get();
            }
            catch(ResourceNotFoundException e){
                return null;
            }
```

It would be good to have support for some sort of method which returns a boolean if the resource exists, or a get method with a default value.

Suggested methods to add into HasOne:

```
public boolean resourceExists(){
    ...
}

public T get(T defaultValue){
   ....
}
```

**Comment by lukesleeman** [comment] 2016-09-07 08:52
I've pulled my proposed HasOne changes from the pull request, so we can discuss further what the methods should be called.  I'm also renaming this issue so it covers both the HasOne and HasMany

**Comment by kamikat** [comment] 2016-09-08 04:52
Made following changes:

- Added `T get(T defaultValue)` to `HasOne<T>` to have default value again if the resource is unavailable. 
- Renamed `T[] HasMany<T>.get()` to `T[] HasMany<T>.getAll()`
- `HasMany<T>` can be iterated with `for` statement without exception when resource cannot be found.

**Comment by lukesleeman** [comment] 2016-09-08 05:11
Awesome!  Are we also able to add a method which checks if the `HasOne` contains something?  Like the `public boolean resourceExists()`?

**Comment by kamikat** [comment] 2016-12-31 09:41
Close the issue because major API changes in 3.x and the issue is no longer useful.
Thanks for your help!

**Closed by kamikat** 2016-12-31 09:41 UTC
Labels: design
